/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import BaseDatos.ConexionActualizarDecimal;
import BaseDatos.ConexionConfigurarSecciones;
import Modelos.AlmacenDTO;
import Modelos.ConfiguracionDeSeccionesDTO;
import Modelos.HospitalDTO;
import Modelos.SeccionesDTO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Configurar_Decimal extends javax.swing.JDialog {
 Logger log=LoggerInfo.getLogger();
 List<SeccionesDTO> secciones=new ArrayList<>();
 HospitalDTO hospital;
 AlmacenDTO almacenPrincipal;
 HospitalDTO hospitalActual;
    public Configurar_Decimal(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        log.info("CREAR / CONFIGURAR DECIMALES");
        GestionDeHospitales.getInstance().llamarDatos();
        hospitalActual=GestionDeHospitales.getInstance().hospitales();
        GestionDeSecciones.getInstance().setIdHospital(hospitalActual.id());
        GestionDeSecciones.getInstance().llamarDatos();
        secciones=GestionDeSecciones.getInstance().secciones();
        
        for(SeccionesDTO seccion: secciones){
            Combo_Secciones.addItem(seccion);
        }
         GestionDeAlmacenes.getInstance().llamarDatos();
        almacenPrincipal= GestionDeAlmacenes.getInstance().almacenPrincipal();
        if(almacenPrincipal != null){
            etiquetaAlmacenActivo.setText(almacenPrincipal.denominacion());
        }else{
             etiquetaAlmacenActivo.setText("NO OBTENIDO");
        }
         GestionDeHospitales.getInstance().llamarDatos();
        hospital=GestionDeHospitales.getInstance().hospitales();
        etiqNombreHospital.setText(hospital.nombre());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etiq_encabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Combo_Secciones = new javax.swing.JComboBox<>();
        Etiq_nombre_seccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoDecimalCosto = new javax.swing.JTextField();
        campoDecimalCantidades = new javax.swing.JTextField();
        etiquetaAlmacenActivo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_aceptar = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        etiqeSimbolo = new javax.swing.JLabel();
        campoSimbolo = new javax.swing.JTextField();
        etiqHospital = new javax.swing.JLabel();
        etiqNombreHospital = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Etiq_encabezado.setText("<html><body><center>Sistema Administrativo de Inventario </body></html>");

        jLabel1.setText("Crear Decimales");

        jLabel2.setText("Seccion:");

        Combo_Secciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_SeccionesActionPerformed(evt);
            }
        });

        jLabel3.setText("Decimal de Costos: ");

        jLabel4.setText("Decimal de Cantidades:");

        campoDecimalCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDecimalCostoActionPerformed(evt);
            }
        });
        campoDecimalCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDecimalCostoKeyTyped(evt);
            }
        });

        campoDecimalCantidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDecimalCantidadesKeyTyped(evt);
            }
        });

        boton_aceptar.setText("Aceptar");
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_aceptar);

        Boton_Salir.setText("Salir");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Salir);

        etiqeSimbolo.setText("Simbolo:");

        campoSimbolo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoSimboloKeyTyped(evt);
            }
        });

        etiqHospital.setText("Hospital:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(etiquetaAlmacenActivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Etiq_nombre_seccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiqeSimbolo)
                                .addGap(143, 143, 143))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(etiqHospital))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoSimbolo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Combo_Secciones, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE)
                                .addComponent(campoDecimalCantidades, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoDecimalCosto))
                            .addComponent(etiqNombreHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAlmacenActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqHospital)
                    .addComponent(etiqNombreHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Etiq_nombre_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoDecimalCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoDecimalCantidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqeSimbolo)
                    .addComponent(campoSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        // TODO add your handling code here:
        int opcion= JOptionPane.showConfirmDialog(null," ¿Seguro desea Salir?. ¡No se conservara nada que no haya guardado!", "Confirmacion de Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //opcion 0= Si, 1=No
         if (opcion==0)
         {
             this.dispose();
         }//if
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
        // TODO add your handling code here:
        
        if(campoDecimalCosto.getText().isEmpty() || campoDecimalCantidades.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            try
            {
            ConexionActualizarDecimal decimal=new ConexionActualizarDecimal();
            SeccionesDTO seccionSeleccionada=(SeccionesDTO) Combo_Secciones.getSelectedItem();
            int codigoSeccion=seccionSeleccionada.codigo();
            decimal.setIdSeccion(codigoSeccion);
            decimal.setIdHospital(hospital.id());
            decimal.setDecimal_costo(Integer.parseInt(campoDecimalCosto.getText().trim()));
            decimal.setDecimal_cantidad(Integer.parseInt(campoDecimalCantidades.getText().trim()));
            decimal.setMoneda_simbolo(campoSimbolo.getText().trim());
            decimal.actualizarDecimal();
               
           if(decimal.resultado()>0)
           {
               JOptionPane.showMessageDialog(null, "Datos actualizados en la seccion correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
           }
           if(decimal.resultado()<=0)
           {
               JOptionPane.showMessageDialog(null, "No se pudieron actualizar los datos", "Error", JOptionPane.ERROR_MESSAGE);
           }
            }
            catch(NumberFormatException | HeadlessException | SQLException  e)
            {
               log.severe(e.getMessage());
                JOptionPane.showMessageDialog(null, "No se pudo actualizar por: "+e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_boton_aceptarActionPerformed

    private void campoDecimalCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDecimalCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDecimalCostoActionPerformed

    private void campoDecimalCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDecimalCostoKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();
        if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/) && (caracter !='.'))
      {
         JOptionPane.showMessageDialog(null, "Este campo solo se admiten numeros", "Revisar", JOptionPane.ERROR_MESSAGE);
         evt.consume();
      }
        else
        {
        if(campoDecimalCosto.getText().trim().length()==1)
        {
            evt.consume();
        }
       
        }
    }//GEN-LAST:event_campoDecimalCostoKeyTyped

    private void campoDecimalCantidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDecimalCantidadesKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/) && (caracter !='.'))
      {
         JOptionPane.showMessageDialog(null, "Este campo solo se admiten numeros", "Revisar", JOptionPane.ERROR_MESSAGE);
         evt.consume();
      }
        else
        {
             if(campoDecimalCantidades.getText().trim().length()==1)
        {
            evt.consume();
        }
        }
    }//GEN-LAST:event_campoDecimalCantidadesKeyTyped

    private void Combo_SeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_SeccionesActionPerformed
        // TODO add your handling code here:
            try{
          SeccionesDTO seccion=(SeccionesDTO)Combo_Secciones.getSelectedItem();
          
        // 2. IMPORTANTE: Validar que no sea nulo (esto evita el error de índice al cargar)
            if (seccion == null) {
                return; 
            }
            ConexionConfigurarSecciones configurar=new ConexionConfigurarSecciones();
            configurar.setCodigoSeccion(seccion.codigo());
            ConfiguracionDeSeccionesDTO configuracion=configurar.consulta();
            if(configuracion!=null){
                campoDecimalCosto.setText(String.valueOf(configuracion.decimalCosto()));
                campoDecimalCantidades.setText(String.valueOf(configuracion.decimalCantidad()));
                  campoSimbolo.setText(configuracion.simbolo());
                Etiq_nombre_seccion.setText(configuracion.nombreSeccion());
            }else{
            campoDecimalCosto.setText("0");
                campoDecimalCantidades.setText("0");
                  campoSimbolo.setText("#");
                Etiq_nombre_seccion.setText("NO ENCONTRADO");
            }
            
            }catch(Exception ex){
            log.severe("ERROR AL CONSULTAR EN LA VENTANA DE CREAR DECIMALES");
            log.severe(ex.toString());
            }
           
            
    }//GEN-LAST:event_Combo_SeccionesActionPerformed

    private void campoSimboloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSimboloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSimboloKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurar_Decimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurar_Decimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurar_Decimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurar_Decimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Configurar_Decimal dialog = new Configurar_Decimal(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Configurar_Decimal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JComboBox<Modelos.SeccionesDTO> Combo_Secciones;
    private javax.swing.JLabel Etiq_encabezado;
    private javax.swing.JLabel Etiq_nombre_seccion;
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JTextField campoDecimalCantidades;
    private javax.swing.JTextField campoDecimalCosto;
    private javax.swing.JTextField campoSimbolo;
    private javax.swing.JLabel etiqHospital;
    private javax.swing.JLabel etiqNombreHospital;
    private javax.swing.JLabel etiqeSimbolo;
    private javax.swing.JLabel etiquetaAlmacenActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
