/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import BaseDatos.ConexionConfigurarAlmacenes;
import BaseDatos.ConexionSecciones;
import Modelos.AlmacenDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class ConfigurarTiposAlmacenes extends javax.swing.JDialog {

 List<String> codigosAlmacenes= new ArrayList<>();
 List<String> descripcionAlmacenes= new ArrayList<>();
 List<AlmacenDTO> listaAlmacenes=new ArrayList<>();
 AlmacenDTO almacenPrincipal;
 int codigoSeccionActual=0;
 Logger log=LoggerInfo.getLogger();

 
    public ConfigurarTiposAlmacenes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // 2. Limpiar el combo y las listas auxiliares antes de llenar
        comboAlmacenes.removeAllItems();
        codigosAlmacenes.clear(); 
        descripcionAlmacenes.clear();
        GestionDeAlmacenes.getInstance().llamarDatos();
        try{
        
        listaAlmacenes=GestionDeAlmacenes.getInstance().almacenes();
        for(AlmacenDTO almacen:listaAlmacenes){
             codigosAlmacenes.add(almacen.codigo());
             descripcionAlmacenes.add(almacen.denominacion());
             comboAlmacenes.addItem(almacen);
             
        }
        
        almacenPrincipal=GestionDeAlmacenes.getInstance().almacenPrincipal();
        if(almacenPrincipal != null){
            etiquetaAlmacenActivo.setText(almacenPrincipal.denominacion());
        }else{
             etiquetaAlmacenActivo.setText("NO OBTENIDO");
        }
        
        ConexionSecciones seccion=new ConexionSecciones();
         seccion.consulta();
         codigoSeccionActual=seccion.codigo_seccion();
            
        }//try
        catch(Exception e)
        {
            log.severe("ERROR AL OBETENER DATOS PARA EL TIPO DE ALMACEN");
            log.severe(e.toString());
            JOptionPane.showMessageDialog(null, "No se han podido obtener datos de los almacenes debido a: \n "+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        Etiq_encabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Panel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        comboAlmacenes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        etiquetaAlmacenActivo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonDespacho = new javax.swing.JRadioButton();
        botonRecibe = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Etiq_encabezado.setText("<html><body><br><center>Sistema Administrativo de Inventario</body></html>");

        jLabel1.setText("Configurar Tipo de Almacen");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel1.add(jButton1);

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        Panel1.add(botonActualizar);

        comboAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlmacenesActionPerformed(evt);
            }
        });

        jLabel2.setText("Modifique el tipo de almacen solo de ser necesario");

        grupoBotones.add(botonDespacho);
        botonDespacho.setText("Despacho");
        jPanel1.add(botonDespacho);

        grupoBotones.add(botonRecibe);
        botonRecibe.setText("Recibe");
        jPanel1.add(botonRecibe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboAlmacenes, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaAlmacenActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAlmacenActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboAlmacenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
             this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
       try{
        AlmacenDTO seleccionado=(AlmacenDTO)comboAlmacenes.getSelectedItem();
        boolean esDespacho=false;
        boolean esDestino=false;
        if(botonDespacho.isSelected()){
           esDespacho=true;
        }
        if(botonRecibe.isSelected()){
            esDestino=true;
        }
        ConexionConfigurarAlmacenes configurar=new ConexionConfigurarAlmacenes();
        configurar.setCodigoAlmacen(seleccionado.codigo());
        configurar.setAlmacenDespacho(esDespacho);
        configurar.setAlmacenDestino(esDestino);
        configurar.setCodigoSeccion(codigoSeccionActual);
        configurar.actualizar();
        if(configurar.getRespuesta()==1){
            JOptionPane.showMessageDialog(null,"Tipo de almacen actualizado exitosamente" , "Informacion", JOptionPane.INFORMATION_MESSAGE);
            //actualizamos la informacion
            GestionDeAlmacenes.getInstance().llamarDatos();
            // Guardamos qué índice estaba seleccionado para que no se mueva el cursor
            int indexSeleccionado = comboAlmacenes.getSelectedIndex();

            comboAlmacenes.removeAllItems();
            codigosAlmacenes.clear();
            descripcionAlmacenes.clear();

            listaAlmacenes = GestionDeAlmacenes.getInstance().almacenes();

            for (AlmacenDTO almacen : listaAlmacenes) {
                codigosAlmacenes.add(almacen.codigo());
                descripcionAlmacenes.add(almacen.denominacion());
                comboAlmacenes.addItem(almacen);
            }
            // Restauramos la selección para que el usuario no pierda donde estaba
            if (indexSeleccionado != -1 && indexSeleccionado < comboAlmacenes.getItemCount()) {
                comboAlmacenes.setSelectedIndex(indexSeleccionado);
            }
          
        }else{
            JOptionPane.showMessageDialog(null,"No se pudo actualizar el tipo de almacen" , "Error", JOptionPane.ERROR_MESSAGE);
        }
       }catch(SQLException ex){
       log.severe(ex.toString());
       }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void comboAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlmacenesActionPerformed
        // TODO add your handling code here:
    // 1. Obtenemos el objeto seleccionado directamente del combo
    AlmacenDTO seleccionado = (AlmacenDTO) comboAlmacenes.getSelectedItem();

    // 2. IMPORTANTE: Validar que no sea nulo (esto evita el error de índice al cargar)
    if (seleccionado == null) {
        return; 
    }

    // 3. Marcamos los botones según el objeto SELECCIONADO (sin bucles)
    // Usamos el booleano directamente para prender o apagar el botón
    botonDespacho.setSelected(seleccionado.despacho());
    botonRecibe.setSelected(seleccionado.destino());

          
           
    }//GEN-LAST:event_comboAlmacenesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTiposAlmacenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTiposAlmacenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTiposAlmacenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurarTiposAlmacenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigurarTiposAlmacenes dialog = new ConfigurarTiposAlmacenes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiq_encabezado;
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JRadioButton botonDespacho;
    private javax.swing.JRadioButton botonRecibe;
    private javax.swing.JComboBox<AlmacenDTO> comboAlmacenes;
    private javax.swing.JLabel etiquetaAlmacenActivo;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
