/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import BaseDatos.ConexionSecciones;
import BaseDatos.ConexionVerAlmacenes;
import BaseDatos.conexionCrearHospitales;
import Modelos.AlmacenDTO;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Crear_Hospital extends javax.swing.JDialog {

LocalDate fecha=LocalDate.now();
Date fecha_creacion=Date.valueOf(fecha);
int seccion_actual;
String almacenActivoMostrar;
    Logger log=LoggerInfo.getLogger();
AlmacenDTO almacenPrincipal=null;
    public Crear_Hospital(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try{
        radioSi.setSelected(true);
        ConexionSecciones seccion=new ConexionSecciones();
        seccion.consulta();
        seccion_actual=seccion.codigo_seccion();
        GestionDeAlmacenes.getInstance().llamarDatos();
        almacenPrincipal= GestionDeAlmacenes.getInstance().almacenPrincipal();
        if(almacenPrincipal != null){
            etiquetaAlmacenActivo.setText(almacenPrincipal.denominacion());
        }else{
             etiquetaAlmacenActivo.setText("NO OBTENIDO");
        }
        
        }catch(Exception e){
            log.severe("ERROR AL CREAR HOSPITAL");
            log.severe(e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        Etiq_encabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Separador1 = new javax.swing.JSeparator();
        etiqueta_codigo = new javax.swing.JLabel();
        etiqueta_denominacion = new javax.swing.JLabel();
        etiqueta_ubicacion = new javax.swing.JLabel();
        etiqueta_tipo = new javax.swing.JLabel();
        panel_boton = new javax.swing.JPanel();
        Boton_Guardar = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        campoRif = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoDireccion = new javax.swing.JTextField();
        radioNo = new javax.swing.JRadioButton();
        radioSi = new javax.swing.JRadioButton();
        etiquetaAlmacenActivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Etiq_encabezado.setText("<html><body><center>Sistema Administrativo de Inventario </body></html>");

        jLabel1.setText("                 Crear Hospitales");

        etiqueta_codigo.setText("Rif");

        etiqueta_denominacion.setText("Nombre");

        etiqueta_ubicacion.setText("Direccion");

        etiqueta_tipo.setText("Activo");

        Boton_Guardar.setText("Guardar");
        Boton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_GuardarActionPerformed(evt);
            }
        });
        panel_boton.add(Boton_Guardar);

        Boton_Salir.setText("Salir");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        panel_boton.add(Boton_Salir);

        campoRif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRifKeyTyped(evt);
            }
        });

        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });

        campoDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDireccionKeyTyped(evt);
            }
        });

        grupoTipo.add(radioNo);
        radioNo.setText("No");

        grupoTipo.add(radioSi);
        radioSi.setText("Si");
        radioSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaAlmacenActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Separador1)
                    .addComponent(panel_boton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta_codigo)
                            .addComponent(etiqueta_denominacion)
                            .addComponent(etiqueta_ubicacion)
                            .addComponent(etiqueta_tipo))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioSi)
                                .addGap(18, 18, 18)
                                .addComponent(radioNo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoRif)
                            .addComponent(campoNombre)
                            .addComponent(campoDireccion))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Etiq_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAlmacenActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta_codigo)
                    .addComponent(campoRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_denominacion)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_ubicacion)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_tipo)
                    .addComponent(radioNo)
                    .addComponent(radioSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(panel_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        // TODO add your handling code here:
        int opcion= JOptionPane.showConfirmDialog(null," ¿Seguro desea Salir?. ¡No se conservara nada que no haya guardado!", "Confirmacion de Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //opcion 0= Si, 1=No
         if (opcion==0)
         {
             this.dispose();
         }//if
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GuardarActionPerformed
        // TODO add your handling code here:
        String temp_codigo=campoRif.getText().trim();
        String temp_denominacion=campoNombre.getText().trim();
        String temp_ubicacion=campoDireccion.getText().trim();
        
        boolean temp_tipo=true;
        if(radioNo.isSelected()){
            temp_tipo=false;//1 para despacho
        }
        if(temp_codigo.isEmpty() || temp_denominacion.isEmpty() || temp_ubicacion.isEmpty())
            {
             JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "Revisar", JOptionPane.ERROR_MESSAGE);
 
            }else
            {
            try {
                conexionCrearHospitales crear=new conexionCrearHospitales();
                crear.setRif(temp_codigo);
                crear.setNombre(temp_denominacion);
                crear.setDireccion(temp_ubicacion);
            
                crear.setFecha_creacion(fecha_creacion);
                crear.setActivo(temp_tipo);
                
               
                crear.crear();
                if(crear.getRespuesta()>0){
                    JOptionPane.showMessageDialog(null, "Hospital creado Exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                    campoRif.setText("");
                    campoNombre.setText("");
                    campoNombre.setText("");
                    campoDireccion.setText("");
                    
                }else
                {
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al crear el Hospital", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                log.severe("ERROR AL CREAR EL ALMACEN");
                log.severe(ex.toString());
            }
            }
            
        
    }//GEN-LAST:event_Boton_GuardarActionPerformed

    private void campoRifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRifKeyTyped
      char caracter=evt.getKeyChar();
         if(campoRif.getText().length()>= 19)
            {
               JOptionPane.showMessageDialog(null, "Este campo admite un maximo de 20 caracteres", "Revisar", JOptionPane.ERROR_MESSAGE);
              evt.consume();
            }//if
    }//GEN-LAST:event_campoRifKeyTyped

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        // TODO add your handling code here:
        char caracter=evt.getKeyChar();
        if(campoNombre.getText().length()>=69)
            {
               JOptionPane.showMessageDialog(null, "Este campo admite un maximo de 70 caracteres", "Revisar", JOptionPane.ERROR_MESSAGE);
              evt.consume();
            }//if
    }//GEN-LAST:event_campoNombreKeyTyped

    private void campoDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDireccionKeyTyped
        // TODO add your handling code here:
        char caracter=evt.getKeyChar();
        if(campoDireccion.getText().length()>=99)
            {
               JOptionPane.showMessageDialog(null, "Este campo admite un maximo de 100 caracteres", "Revisar", JOptionPane.ERROR_MESSAGE);
              evt.consume();
            }//if
    }//GEN-LAST:event_campoDireccionKeyTyped

    private void radioSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Crear_Hospital dialog = new Crear_Hospital(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Guardar;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JLabel Etiq_encabezado;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoRif;
    private javax.swing.JLabel etiquetaAlmacenActivo;
    private javax.swing.JLabel etiqueta_codigo;
    private javax.swing.JLabel etiqueta_denominacion;
    private javax.swing.JLabel etiqueta_tipo;
    private javax.swing.JLabel etiqueta_ubicacion;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_boton;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioSi;
    // End of variables declaration//GEN-END:variables
}
