/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import BaseDatos.ConexionValidarLogin;
import BaseDatos.SesionUsuario;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Optional;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import shca.inventario.ConfiguracionBaseDatosHospital;

/**
 *
 * @author Informatic HSDM
 */
public class Login extends javax.swing.JFrame {
    Logger log=LoggerInfo.getLogger();
    public Dimension resolucion;
    String esquemaUsuario;
    public Login() {
        initComponents();
    
    }
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqTitulo = new javax.swing.JLabel();
        etiqLogin = new javax.swing.JLabel();
        etiqPassword = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoPassword = new javax.swing.JPasswordField();
        panelBoton = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqTitulo.setText("Sistema Administrativo de Inventario");

        etiqLogin.setText("Login:");

        etiqPassword.setText("Password:");

        panelBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCancelar.setText("Salir");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBoton.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        panelBoton.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(etiqTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqLogin)
                                    .addComponent(etiqPassword))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoLogin)
                                    .addComponent(campoPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(etiqTitulo)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqLogin)
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqPassword)
                    .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(panelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
            int opcion= JOptionPane.showConfirmDialog(null," ¿Seguro desea Salir?. ¡No se conservara nada que no haya guardado!", "Confirmacion de Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //opcion 0= Si, 1=No
         if (opcion==0)
         {
             System.exit(0);
         }//if
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        String usuario=campoLogin.getText().trim();
        String password=campoPassword.getText().trim();
        if(usuario.isBlank() || usuario.isEmpty() || password.isBlank() || password.isEmpty()){
        JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                ConexionValidarLogin login=new ConexionValidarLogin();
                login.setEsquema("public");
                login.setLoggin(usuario);
                login.setPassword(password);
                login.consultar();
                esquemaUsuario=login.getEsquemaRespuesta();
                Optional<String> rolOpt = Optional.ofNullable(login.getRol());
                if(rolOpt.isEmpty()){
                    
                    JOptionPane.showMessageDialog(null, "Usuario no encontrado. Verifique sus datos", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }else{
                    if(login.isEstado()){
                        String rolReal = rolOpt.get();
                        switch(rolReal){
                            
                            case "ADMIN" ->{
                                VentanaAdmin admin = new VentanaAdmin();
                                admin.setLocationRelativeTo(null);
                                admin.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                                admin.setVisible(true);
                                this.dispose();
                            }
                            case "USER" ->{
                                // 1. ANTES de abrir la ventana, mandamos a actualizar el esquema del hospital
                                ConfiguracionBaseDatosHospital configHospital = new ConfiguracionBaseDatosHospital();
                                configHospital.setEsquemas(esquemaUsuario); // El esquema que viene de la tabla login (ej: hsdm)
                                configHospital.migracion(); // <--- Flyway revisará y aplicara
                               // 2. Ahora sí, iniciamos sesión normal
                                SesionUsuario.inicializarSesion(esquemaUsuario, usuario, rolReal);
                                Ventana_Principal ventana = new Ventana_Principal();
                                ventana.setLocationRelativeTo(null);
                                // ventana.setResizable(false);
                                ventana.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                                ventana.setVisible(true);
                                this.dispose();
                            }
                        }
                    }//if
                    else{
                        JOptionPane.showMessageDialog(null, "Usuario inactivo", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                }   
            } catch (SQLException ex) {
                  log.severe("ERROR AL VALIDAR EL LOGIN");
                  log.severe(ex.toString());
                }
        }
        
        
       
        
    }//GEN-LAST:event_botonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JLabel etiqLogin;
    private javax.swing.JLabel etiqPassword;
    private javax.swing.JLabel etiqTitulo;
    private javax.swing.JPanel panelBoton;
    // End of variables declaration//GEN-END:variables
}
