package inventario;

import BaseDatos.ConexionControlDeInicio;
import BaseDatos.ConexionSecciones;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

       
public class Ventana_Principal extends javax.swing.JFrame {
   
    String nombre;//nombre tomado al iniciar el programa
    Logger log=LoggerInfo.getLogger();
    ConexionControlDeInicio inicio=new ConexionControlDeInicio();
  
      
    
    public Ventana_Principal() {
      
        initComponents();
        try{
            log.info("VENTANA PRINCIPAL CARGADA");
       
        this.getContentPane().setBackground(Color.WHITE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        
        ConexionSecciones consulta_secciones=new ConexionSecciones();
        consulta_secciones.consulta();
        nombre=consulta_secciones.nombre_seccion();
       if(nombre==null)
        {
            log.severe("NO SE PUDO OBTENER INFORMACION DE LA SECCION EN CUAL TRABAJAR");
            JOptionPane.showMessageDialog(null, "No se pudo Obtener la informacion de la Seccion en cual trabajar.\n Ventana Principal \n Contacte al Desarrollador \n " ,  "ERROR GRAVE", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        else
        {
       Etiq_titulo.setText(nombre);
        }
       
       //mejorar el menu JTree:
                // Elimina las líneas que unen los nodos
         Arbol.putClientProperty("JTree.lineStyle", "None");

         // Aumenta la altura de las filas (fundamental para que parezca un menú)
         Arbol.setRowHeight(35); 

         // Oculta el nodo raíz (el que dice "Menú" o "Inicio") para que se vea más limpio
         Arbol.setRootVisible(false);
         Arbol.setShowsRootHandles(true); // Muestra las flechitas para desplegar
             
       }catch(Exception e){
        log.severe("ERROR AL EJECUTAR LA VENTANA PRINCIPAL");
        log.severe(e.toString());
        }
      
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();
        Etiq_Seccion = new javax.swing.JLabel();
        Etiq_titulo = new javax.swing.JLabel();
        Boton_cambiar = new javax.swing.JButton();
        PanelLayout = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        etiquetaVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Inventario");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Entradas");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Salidas");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Proveedores");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Proveedores");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Servicios");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Servicios");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Almacenes");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Crear");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Consultar");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Principal");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Tipos");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Hospitales");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Consultar");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Reportes");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Reportes");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Configuracion");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Firmantes");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Secciones");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Unidades");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Cargos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Conceptos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Grupos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Decimales");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        Arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        Arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Arbol);

        Etiq_Seccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Etiq_Seccion.setText("SECCION:");

        Etiq_titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        Boton_cambiar.setText("Cambiar");
        Boton_cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_cambiarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        PanelLayout.add(botonSalir);

        etiquetaVersion.setText("Ver1.1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Etiq_Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Etiq_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton_cambiar)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addComponent(etiquetaVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Etiq_Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Etiq_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Boton_cambiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaVersion)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       //metodo para lanzar las ventanas
    private void lanzarVentana(JDialog ventana) {
            ventana.setResizable(false);
            ventana.setLocationRelativeTo(this); // se centra en tu App
            ventana.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
            ventana.setVisible(true);
        }   
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
       
             int opcion= JOptionPane.showConfirmDialog(null," ¿Seguro desea Salir?. ¡No se conservara nada que no haya guardado!", "Confirmacion de Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //opcion 0= Si, 1=No
         if (opcion==0)
         {
            
                 try {
                     inicio.cerrar();
                 } catch (SQLException ex) {
                     log.severe(ex.toString());
                 }
             System.exit(0);
         }//if
                 
    }//GEN-LAST:event_botonSalirActionPerformed

    private void ArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArbolMouseClicked
        // TODO add your handling code here:
       if (evt.getClickCount() == 2) {
    DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) Arbol.getLastSelectedPathComponent();

    // 1. Validaciones preventivas (Anti-Error)
    if (nodo == null || !nodo.isLeaf()) {
        return; // Si no hay selección o es un nodo padre, no hacemos nada
    }

    // 2. Extraemos info limpia
    String hijo = nodo.getUserObject().toString();
    String padre = (nodo.getParent() != null) ? nodo.getParent().toString() : "";

    // 3. El Switch Maestro
    switch (padre) {
        case "Inventario" -> {
            if (hijo.equals("Entradas")) {
              //  Consultar_Entradas v = new Consultar_Entradas(this, true);
              Entradas_Inventario v = new Entradas_Inventario(this, true);
              v.PrincipalFrame(this);
                lanzarVentana(v);
            } else if (hijo.equals("Salidas")) {
                Consultar_Salidas v = new Consultar_Salidas(this, true);
                v.PrincipalFrame(this);
                lanzarVentana(v);
            }  }

        case "Proveedores" -> {
            if (hijo.equals("Proveedores")) lanzarVentana(new Proveedores(this, true));
               }
        case "Servicios" -> {
            if (hijo.equals("Servicios")) lanzarVentana(new Servicios(this, true));
               }

        case "Almacenes" -> {
            if (hijo.equals("Crear")) try {
                lanzarVentana(new Crear_Almacenes(this, true));
            } catch (SQLException ex) {
                log.severe("ERROR AL LANZAR LA VENTANA DE CREAR ALMANACENES");
                log.severe(ex.toString());
            }
            if (hijo.equals("Consultar")) lanzarVentana(new Consultar_Almacenes(this, true));
            if (hijo.equals("Principal")) lanzarVentana(new ConfigurarAlmacenPrincipal(this, true));
            if (hijo.equals("Tipos")) lanzarVentana(new ConfigurarTiposAlmacenes(this, true));
               }
        case "Hospitales" -> {
            if (hijo.equals("Consultar")) lanzarVentana(new Consultar_Hospital(this, true));

        
        }
        case "Articulos" ->{
            if (hijo.equals("Articulos")) lanzarVentana(new Articulos(this, true));
                   
        }
        case "Firmantes" -> {
            if (hijo.equals("Configurar")) lanzarVentana(new VerFirmantes(this, true));

        }
        case "Reportes"->{
           if (hijo.equals("Reportes")) lanzarVentana(new Reportes(this, true));

        }
            
        case "Configuracion" -> {
            if (hijo.equals("Secciones")) try {
                lanzarVentana(new Crear_Secciones(this, true));
            } catch (SQLException ex) {
                log.severe("ERROR AL LANZAR LA VENTANA DE CREAR SECCIONES");
                log.severe(ex.toString());
            }
            if (hijo.equals("Unidades")) lanzarVentana(new Crear_Unidades(this, true));
            if (hijo.equals("Firmantes")) lanzarVentana(new Firmantes(this, true));
            if (hijo.equals("Cargos")) lanzarVentana(new Cargos(this, true));
            if (hijo.equals("Conceptos")) lanzarVentana(new Crear_Conceptos(this, true));
            if (hijo.equals("Grupos")) lanzarVentana(new Crear_Grupos(this, true));
            if (hijo.equals("Decimales")) try {
                lanzarVentana(new Configurar_Decimal(this, true));
            } catch (SQLException ex) {
                log.severe("ERROR AL LANZAR LA VENTANA DE CREAR DECIMALES");
                log.severe(ex.toString());
            }  
        }
    }//switch
}//2 click
        
        
    }//GEN-LAST:event_ArbolMouseClicked

    private void Boton_cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_cambiarActionPerformed
        // TODO add your handling code here:
        try{ 
        Ver_Secciones seccion= new Ver_Secciones(null, true);
         seccion.setResizable(false);
         seccion.setLocationRelativeTo(null);
         seccion.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         seccion.setVisible(true);
       
       if(seccion.getEstado()==1)
       {
           ConexionSecciones consulta_seccion=new ConexionSecciones();
            consulta_seccion.consulta();
            nombre=consulta_seccion.nombre_seccion();
            Etiq_titulo.setText(nombre);
       }
        }catch(Exception e){
        log.severe("ERROR AL EJECUTAR EL CAMBIO DE SECCION");
        log.severe(e.toString());
        }
        
    }//GEN-LAST:event_Boton_cambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Arbol;
    private javax.swing.JButton Boton_cambiar;
    private javax.swing.JLabel Etiq_Seccion;
    private javax.swing.JLabel Etiq_titulo;
    private javax.swing.JPanel PanelLayout;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaVersion;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
