/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import BaseDatos.ConexionActualizarHospitalEsquema;
import BaseDatos.ConexionControlDeInicio;
import BaseDatos.ConexionCrearConfiguracionInicialHospitales;
import BaseDatos.ConexionCrearConfiguracionInicialUsuarios;
import BaseDatos.ConexionVerConfigHospitales;
import BaseDatos.ConexionVerUsuarios;
import BaseDatos.SesionUsuario;
import Modelos.ConfigHospitalDTO;
import Modelos.UsuarioDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shca.inventario.ConfiguracionBaseDatosHospital;

/**
 *
 * @author USER
 */
public class VentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    ConexionControlDeInicio inicio=new ConexionControlDeInicio();
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    List<ConfigHospitalDTO> listaHospitales=new ArrayList<>();
    List<UsuarioDTO> listaUsuarios=new ArrayList<>();
    private static Logger log=LoggerInfo.getLogger();
    String esquema="public";//se hacen estas consultas al esquema public
    int operacion=0;//1 para crear y 2 para actualizar
    int idSeleccionado=0;
    public VentanaAdmin() throws SQLException {
             initComponents();
        panelFormularioHospital.setVisible(false);
        panelFormularioUsuario.setVisible(false);
        botonSi.setSelected(true);
        llenarTabla(); 
    }
    
    private void llenarTabla(){
            try{
                
        idSeleccionado=0;
        operacion=0;
        modelo=(DefaultTableModel)tablaHospitales.getModel();
        modelo2=(DefaultTableModel)tablaUsuarios.getModel();
        modelo.setRowCount(0);
        modelo2.setRowCount(0);
        ConexionVerUsuarios usuarios=new ConexionVerUsuarios();
        usuarios.setEsquema(esquema);
        listaUsuarios=usuarios.consultar();
        ConexionVerConfigHospitales hospitales= new ConexionVerConfigHospitales();
        hospitales.setEsquema(esquema);
        listaHospitales=hospitales.consultar();
        for(ConfigHospitalDTO hosps: listaHospitales ){
            modelo.addRow(new Object[]{hosps.idHospital(), hosps.rif(), hosps.nombreHospital(), hosps.nombreEsquema()});
            comboHospital.addItem(hosps);
        }
        for(UsuarioDTO users: listaUsuarios ){
            modelo2.addRow(new Object[]{users.id(), users.usuario(), users.password(), users.rol(), users.nombreHospital(), users.estado()});
        }
        }catch(Exception ex){
        log.severe("ERROR AL LLENAR LAS TABLAS DEL ADMIN");
        log.severe(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBoton = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHospitales = new javax.swing.JTable();
        panelFormularioHospital = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textDireccion = new javax.swing.JTextArea();
        campoRif = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoEsquema = new javax.swing.JTextField();
        botonGuardarHospital = new javax.swing.JButton();
        panelBoton2 = new javax.swing.JPanel();
        botonCrearHospital = new javax.swing.JButton();
        botonActualizarHospital = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        panelBoton = new javax.swing.JPanel();
        botonCrearUsuario = new javax.swing.JButton();
        botonActualizarUsuario = new javax.swing.JButton();
        panelFormularioUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboRol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonSi = new javax.swing.JRadioButton();
        botonNo = new javax.swing.JRadioButton();
        comboHospital = new javax.swing.JComboBox<>();
        botonGuardarUsuario = new javax.swing.JButton();
        panelBoton1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaHospitales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Rif", "Hospital", "Esquema"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaHospitales);

        panelFormularioHospital.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Rif:");
        panelFormularioHospital.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 3, -1, -1));

        jLabel7.setText("Nombre:");
        panelFormularioHospital.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 31, -1, -1));

        jLabel8.setText("Esquema:");
        panelFormularioHospital.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));

        jLabel9.setText("Direccion:");
        panelFormularioHospital.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, -1, -1));

        textDireccion.setColumns(20);
        textDireccion.setRows(5);
        jScrollPane3.setViewportView(textDireccion);

        panelFormularioHospital.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 96, 850, -1));
        panelFormularioHospital.add(campoRif, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 0, 850, -1));
        panelFormularioHospital.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 28, 850, -1));
        panelFormularioHospital.add(campoEsquema, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 68, 850, -1));

        botonGuardarHospital.setText("Guardar");
        botonGuardarHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarHospitalActionPerformed(evt);
            }
        });
        panelFormularioHospital.add(botonGuardarHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        botonCrearHospital.setText("Crear");
        botonCrearHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearHospitalActionPerformed(evt);
            }
        });
        panelBoton2.add(botonCrearHospital);

        botonActualizarHospital.setText("Actualizar");
        botonActualizarHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarHospitalActionPerformed(evt);
            }
        });
        panelBoton2.add(botonActualizarHospital);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE))
                    .addComponent(panelFormularioHospital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBoton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFormularioHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPrincipal.addTab("Hospitales", jPanel2);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Username", "Pasword", "Rol", "Hospital", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        botonCrearUsuario.setText("Crear");
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });
        panelBoton.add(botonCrearUsuario);

        botonActualizarUsuario.setText("Actualizar");
        botonActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarUsuarioActionPerformed(evt);
            }
        });
        panelBoton.add(botonActualizarUsuario);

        panelFormularioUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username: ");
        panelFormularioUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));
        panelFormularioUsuario.add(campoUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 6, 850, -1));

        jLabel2.setText("Password:");
        panelFormularioUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, -1, -1));
        panelFormularioUsuario.add(campoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 40, 850, -1));

        jLabel3.setText("Rol:");
        panelFormularioUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));

        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER", "ADMIN" }));
        panelFormularioUsuario.add(comboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 68, 313, -1));

        jLabel4.setText("Activo:");
        panelFormularioUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 98, -1, -1));

        jLabel5.setText("Hospital:");
        panelFormularioUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        grupoBoton.add(botonSi);
        botonSi.setText("Si");
        panelFormularioUsuario.add(botonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 96, -1, -1));

        grupoBoton.add(botonNo);
        botonNo.setText("No");
        panelFormularioUsuario.add(botonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 96, -1, -1));

        panelFormularioUsuario.add(comboHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 862, -1));

        botonGuardarUsuario.setText("Guardar");
        botonGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarUsuarioActionPerformed(evt);
            }
        });
        panelFormularioUsuario.add(botonGuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 200, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFormularioUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFormularioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        panelPrincipal.addTab("Usuarios", jPanel1);

        panelBoton1.setLayout(new java.awt.BorderLayout());

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelBoton1.add(botonSalir, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBoton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPrincipal))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelPrincipal)
                .addGap(18, 18, 18)
                .addComponent(panelBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        try{
       
             System.exit(0);
                    
        }catch(Exception ex){
        log.severe("HA OCURRIDO UN ERROR AL CERRAR LA APLICACION EN ADMIN");
        log.severe(ex.toString());
        }
        
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonGuardarHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarHospitalActionPerformed
        // TODO add your handling code here:
        String rif=campoRif.getText().trim();
        String hospital=campoNombre.getText().trim().toUpperCase();
        String escheme=campoEsquema.getText().trim();
        String direccion=textDireccion.getText().trim();
        if (
              rif.isBlank() || rif.isEmpty() ||
              hospital.isBlank() || hospital.isEmpty()||
              escheme.isBlank() || escheme.isEmpty()||
              direccion.isBlank() || direccion.isEmpty()
                
                
            ){
        JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            
                if(operacion==1)//es decir crear
                {
                    try{
                           //creo el esquema en BD
                              ConfiguracionBaseDatosHospital configurarEsquema=new ConfiguracionBaseDatosHospital();
                              configurarEsquema.setEsquemas(escheme);
                              configurarEsquema.migracion();
                              
                              //el esquema existe asi procedo a crear el hospital
                            ConexionCrearConfiguracionInicialHospitales crearConfig=new ConexionCrearConfiguracionInicialHospitales();
                            crearConfig.setEsquemaConexion(esquema);
                            crearConfig.setRif(rif);
                            crearConfig.setDireccion(direccion);
                            crearConfig.setNombre(hospital);
                            crearConfig.setEsquemaCreado(escheme);
                            crearConfig.crearHospital();
                            if(crearConfig.respuesta()==1){
                                
                              //actualizo el hospital a ese esquema que le asigne
                              ConexionActualizarHospitalEsquema actualizarHospital= new ConexionActualizarHospitalEsquema();
                              actualizarHospital.setEsquema(escheme);
                              actualizarHospital.setRif(rif);
                              actualizarHospital.setNombre(hospital);
                              actualizarHospital.setDireccion(direccion);
                              actualizarHospital.actualizarHospital();
                              
                              JOptionPane.showMessageDialog(null, "Hospital creado exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                              
                              operacion=0;
                              campoNombre.setText("");
                              campoRif.setText("");
                              campoEsquema.setText("");
                              textDireccion.setText("");
                              llenarTabla();
                              panelFormularioHospital.setVisible(false);
                             
                              
                            }else{
                              JOptionPane.showMessageDialog(null, "Error al crear el hospital", "Error", JOptionPane.ERROR_MESSAGE);

                        }
                    }catch(Exception ex){
                    log.severe("ERROR AL CREAR HOSPITAL EN BD PUBLIC");
                    log.severe(ex.toString());
                    }
                
                }
                if(operacion==2){
                
                    try{
                        
                            ConexionCrearConfiguracionInicialHospitales crearConfig=new ConexionCrearConfiguracionInicialHospitales();
                            crearConfig.setEsquemaConexion(esquema);
                            crearConfig.setRif(rif);
                            crearConfig.setDireccion(direccion);
                            crearConfig.setNombre(hospital);
                            crearConfig.setEsquemaCreado(escheme);
                            crearConfig.setIdHospital(idSeleccionado);
                            crearConfig.actualizarHospital();
                            
                            if(crearConfig.respuesta()==1){
                                 //actualizo el hospital a ese esquema que le asigne
                              ConexionActualizarHospitalEsquema actualizarHospital= new ConexionActualizarHospitalEsquema();
                              actualizarHospital.setEsquema(escheme);
                              actualizarHospital.setRif(rif);
                              actualizarHospital.setNombre(hospital);
                              actualizarHospital.setDireccion(direccion);
                              actualizarHospital.actualizarHospital();
                                
                              JOptionPane.showMessageDialog(null, "Hospital actualizado exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                              operacion=0;
                              campoNombre.setText("");
                              campoRif.setText("");
                              campoEsquema.setText("");
                              textDireccion.setText("");
                              llenarTabla();
                              panelFormularioHospital.setVisible(false);
                            }else{
                              JOptionPane.showMessageDialog(null, "Error al actualizar el hospital", "Error", JOptionPane.ERROR_MESSAGE);

                        }
                    }catch(Exception ex){
                    log.severe("ERROR AL ACTUALIZAR HOSPITAL EN BD PUBLIC");
                    log.severe(ex.toString());
                    }
                
                
                }
                
        }
        
        
        
        
    }//GEN-LAST:event_botonGuardarHospitalActionPerformed

    private void botonCrearHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearHospitalActionPerformed
        // TODO add your handling code here:
        operacion=1;
        panelFormularioHospital.setVisible(true);
    }//GEN-LAST:event_botonCrearHospitalActionPerformed

    private void botonActualizarHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarHospitalActionPerformed
        // TODO add your handling code here:
        operacion=2;
        int filaSeleccionada=tablaHospitales.getSelectedRow();
             if (filaSeleccionada != -1){
                 // (Importante por si el usuario ordenó la tabla haciendo clic en las cabeceras)
             int indiceReal = tablaHospitales.convertRowIndexToModel(filaSeleccionada);
             ConfigHospitalDTO hospitalSeleccionado=listaHospitales.get(indiceReal);
             campoRif.setText(hospitalSeleccionado.rif());
             campoNombre.setText(hospitalSeleccionado.nombreHospital());
             campoEsquema.setText(hospitalSeleccionado.nombreEsquema());
             campoEsquema.setEditable(false);
             textDireccion.setText(hospitalSeleccionado.direccion());
             idSeleccionado=hospitalSeleccionado.idHospital();
             panelFormularioHospital.setVisible(true);
             
             }else{
                 JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);

               }
        
    }//GEN-LAST:event_botonActualizarHospitalActionPerformed

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        // TODO add your handling code here:
        operacion=1;
        panelFormularioUsuario.setVisible(true);
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void botonGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarUsuarioActionPerformed
        // TODO add your handling code here:
        
        String username=campoUsername.getText().trim();
        String password=campoPassword.getText().trim();
        String rol=(String) comboRol.getSelectedItem();
        boolean estado=true;
        if(botonSi.isSelected()){estado=true;}
        if(botonNo.isSelected()){estado=false;}
        ConfigHospitalDTO hospitalSeleccionado=(ConfigHospitalDTO)comboHospital.getSelectedItem();
        int idHospital=hospitalSeleccionado.idHospital();
        
        if(
           username.isBlank()|| username.isEmpty()||
           password.isBlank() || password.isEmpty()
                )
        
        
        {
           JOptionPane.showMessageDialog(null, "debe completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);

        
        }else{
            if(operacion==1){
                try {
                    ConexionCrearConfiguracionInicialUsuarios usuarios=new ConexionCrearConfiguracionInicialUsuarios();
                    usuarios.setEsquemaConexion(esquema);
                    usuarios.setUsername(username);
                    usuarios.setPassword(password);
                    usuarios.setRol(rol);
                    usuarios.setIdHospital(idHospital);
                    usuarios.setEstado(estado);
                    usuarios.crearUsuario();
                    if(usuarios.respuesta()==1){
                     JOptionPane.showMessageDialog(null, "Usuario creado exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                     campoUsername.setText("");
                     campoPassword.setText("");
                     comboRol.setSelectedIndex(0);
                     botonSi.setSelected(true);
                     panelFormularioUsuario.setVisible(false);
                     llenarTabla();
                    
                    }else{
                     JOptionPane.showMessageDialog(null, "error al crear el usuario", "Error", JOptionPane.ERROR_MESSAGE);

                    }
                } catch (SQLException ex) {
                    log.severe("ERROR AL CREAR EL USUARIO");
                    log.severe(ex.toString());
                }


                    }
            
            
            if(operacion==2){
            
             try {
                    ConexionCrearConfiguracionInicialUsuarios usuarios=new ConexionCrearConfiguracionInicialUsuarios();
                    usuarios.setEsquemaConexion(esquema);
                    usuarios.setUsername(username);
                    usuarios.setPassword(password);
                    usuarios.setRol(rol);
                    usuarios.setIdUsuario(idSeleccionado);
                    usuarios.setIdHospital(idHospital);
                    usuarios.setEstado(estado);
                    usuarios.actualizarUsuario();
                    if(usuarios.respuesta()==1){
                     JOptionPane.showMessageDialog(null, "Usuario actualizado exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                   
                     campoUsername.setText("");
                     campoPassword.setText("");
                     comboRol.setSelectedIndex(0);
                     botonSi.setSelected(true);
                     panelFormularioUsuario.setVisible(false);
                     llenarTabla();
                    }else{
                     JOptionPane.showMessageDialog(null, "error al actualizar el usuario", "Error", JOptionPane.ERROR_MESSAGE);

                    }
                } catch (SQLException ex) {
                    log.severe("ERROR AL CREAR EL USUARIO");
                    log.severe(ex.toString());
                }
            }
        
        }
        
        
        
    }//GEN-LAST:event_botonGuardarUsuarioActionPerformed

    private void botonActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarUsuarioActionPerformed
        // TODO add your handling code here:
         operacion=2;
        int filaSeleccionada=tablaUsuarios.getSelectedRow();
             if (filaSeleccionada != -1){
              
                 // (Importante por si el usuario ordenó la tabla haciendo clic en las cabeceras)
             int indiceReal = tablaUsuarios.convertRowIndexToModel(filaSeleccionada);
             UsuarioDTO usuarioSeleccionado=listaUsuarios.get(indiceReal);
             idSeleccionado=usuarioSeleccionado.id();
             campoUsername.setText(usuarioSeleccionado.usuario());
             campoPassword.setText(usuarioSeleccionado.password());
             if(usuarioSeleccionado.estado()){
             botonSi.setSelected(true);
             }else{
             botonNo.setSelected(true);
             }
             if(usuarioSeleccionado.rol().equals("USER")){
             comboRol.setSelectedItem("USER");
             }else{
             comboRol.setSelectedItem("ADMIN");
             }
             int hospitalSeleccionado=usuarioSeleccionado.idHospital();
             for(int i=0; i<comboHospital.getItemCount(); i++){
                  ConfigHospitalDTO hospital=(ConfigHospitalDTO)comboHospital.getItemAt(i);
                  if(hospitalSeleccionado==hospital.idHospital()){
                      
                      comboHospital.setSelectedIndex(i);
                      break;
                  }
                  
             }
             panelFormularioUsuario.setVisible(true);
             }
             
            
            
             else{
                 JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);

               }
    }//GEN-LAST:event_botonActualizarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaAdmin().setVisible(true);
                } catch (SQLException ex) {
log.severe("ERROR AL CARGAR VENTANA ADMIN");
log.severe(ex.toString());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarHospital;
    private javax.swing.JButton botonActualizarUsuario;
    private javax.swing.JButton botonCrearHospital;
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JButton botonGuardarHospital;
    private javax.swing.JButton botonGuardarUsuario;
    private javax.swing.JRadioButton botonNo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JRadioButton botonSi;
    private javax.swing.JTextField campoEsquema;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPassword;
    private javax.swing.JTextField campoRif;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JComboBox<ConfigHospitalDTO> comboHospital;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.ButtonGroup grupoBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelBoton1;
    private javax.swing.JPanel panelBoton2;
    private javax.swing.JPanel panelFormularioHospital;
    private javax.swing.JPanel panelFormularioUsuario;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JTable tablaHospitales;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextArea textDireccion;
    // End of variables declaration//GEN-END:variables
}
